### ISSUE TITLE
HalDeserializer for customers fails

### ISSUE THREAD

**Issue by senghe** [helpscout/helpscout-api-php#89] opened 2019-02-07 08:54 UTC
Hi. I'm use API SDK in 2.0.2 version. When I run code:

```
$helpscoutClient = HelpScout\Api\ApiClientFactory::createClient();
$helpscoutClient->useClientCredentials($appId, $appSecret)
$helpscoutClient->customers()->list();
```

I have en error message:

`In HalDeserializer.php line 119:                                                                         
Argument 1 passed to HelpScout\Api\Http\Hal\HalDeserializer::HelpScout\Api\Http\Hal\{closure}() must be of the type array, string given`

From my debugging looks that customer address parts are string, but it should be arrays. Could you look at this?

**Comment by davidstanley01** [comment] 2019-02-18 19:11
Hrm... I see what the issue is. I'll get to work on a fix for this.

**Comment by bkuhl** [comment] 2019-03-05 22:09
@senghe Thanks for reporting this issue.  We've just pushed up a PR that resolves the issue.  We'll ship it once it's merged.  This issue became more apparent when an update was made to our API that [loaded all customer entries by default](https://developer.helpscout.com/mailbox-api/changelog/#2019-01-25-new-return-all-customer-entries-always).

**Comment by bkuhl** [comment] 2019-03-18 17:22
This is resolved with https://github.com/helpscout/helpscout-api-php/releases/tag/2.0.4 so I'm closing this out.

**Closed by bkuhl** 2019-03-18 17:22 UTC
Labels: bug
